title: Ethan Gardners Software Blog 
description: > # this means to ignore newlines until "baseurl:"
  I am some sort of engineer
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.codewandering.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here
# Author Settings
author: Ethan Gardner # add your name
author-img: ethan-hammock.jpg # add your photo
about-author: I am some sort of engineer. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: https://github.com/emg184 # add your Github handle
social-linkedin: https://www.linkedin.com/in/ethan-gardner-06261988/ # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: ethanmgardner # add your discus identifier

# Tracker
analytics: UA-155315616-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
